### ISSUE TITLE
undefined reference to `spoof_call2'

### ISSUE THREAD

**Issue by bcdlbgm** [Kudaes/Unwinder#3]
target\release\deps\apc-772f286d6c12883d.apc.bad2967599c135d4-cgu.0.rcgu.o:apc.bad2967599c135:(.text+0x38b79): undefined reference to `spoof_call2'

Using replace and syscall will cause errors during compilation;
nightly-x86_64-pc-windows-gnu
rustup 1.26.0 (5af9b9484 2023-04-05)
rustc 1.78.0-nightly (ef324565d 2024-02-27)
cargo 1.78.0-nightly (194a60b29 2024-02-21)

**Comment by Kudaes** [comment]
Use the toolchain set in `.cargo\config` file: x86_64-pc-windows-msvc. Let me know if that solves the issue.

**Comment by bcdlbgm** [comment]
yes issue was solved.thanks


不成大佬不改名！
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kudaes/Unwinder"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年6月11日(星期二) 晚上7:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kudaes/Unwinder] undefined reference to `spoof_call2' (Issue #3)





 
Use the toolchain set in .cargo\config file: x86_64-pc-windows-msvc. Let me know if that solves the issue.

**Comment by Kudaes** [comment]
Great

**Comment by Kudaes** [comment]
Great
